spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Loans Service on QA environment"
  contactDetails:
    name: "Gracjan Lukaszewicz - Developer"
    email: "gracjan.luk@gmail.com"